from __future__ import annotations

from typing import Dict, List, Protocol

from arc.util.io import Reads


class _Block(Protocol):
    name: str
    size: int
    rotate: bool
    sizeOffset: int

class _Color(Protocol):
    r: float
    g: float
    b: float
    a: float

class _Item(Protocol):
    name: str
    color: _Color

class _ItemStack(Protocol):
    item: _Item
    amount: int = 0

class _Schematic(Protocol):
    tiles: List[_Stile]
    labels: List[str]
    tags: Dict[str, str]
    width: int
    height: int

    def powerProduction(self) -> float: ...
    def powerConsumption(self) -> float: ...
    def requirements(self) -> List[_ItemStack]: ...
    def name(self) -> str: ...
    def description(self) -> str: ...

    class _Stile(Protocol):
        block: _Block
        x: int
        y: int
        config: object
        rotation: bytes

class _Reads(Protocol):
    def checkEOF(self) -> int: ...
    def l(self) -> int: ...
    def i(self) -> int: ...
    def s(self) -> int: ...
    def b(self) -> bytes: ...
    def b(self, length: int) -> List[bytes]: ...    
    def b(self, array: List[bytes]) -> List[bytes]: ...
    def b(self, array: List[bytes], offset: int, length: int) -> List[bytes]: ...
    def ub(self) -> int: ...
    def bool(self) -> bool: ...
    def f(self) -> float: ...
    def str(self) -> str: ...
    ...

class _Fi(Protocol):
    def child(self, name: str) -> _Fi: ...
    def parent(self) -> _Fi: ...
    def reads(self) -> Reads: ...
    def path(self) -> str: ...
    def mkdirs(self) -> bool: ...